//! Bootstrap-time Terraform rules-pack emitter for the GCP Cloud Run env-pack.
//!
//! Mirrors the AWS-ECS [`bootstrap`](crate::env_packs::aws::bootstrap): renders
//! a minimum-privilege setup the customer's admin reviews and `tofu apply` /
//! `terraform apply` against their own GCP project. Two files land under
//! `<env_root>/rules/greentic.deployer.gcp-cloudrun/`:
//!
//! - `gcp-cloudrun-bootstrap.tf` — a deployer service account, a runtime
//!   service account, a minimum-privilege custom IAM role bound to the deployer
//!   SA (permissions sourced from
//!   [`VALIDATED_GCP_PERMISSIONS`](super::credentials::VALIDATED_GCP_PERMISSIONS),
//!   the exact list `validate` probes), `google_project_service` enablement for
//!   Cloud Run + Secret Manager, and — commented out, opt-in — the Artifact
//!   Registry API + a remote repository proxying ghcr.io for the
//!   higher-availability case (plan D3/D7). AR is off by default because a
//!   remote repo bills for cached-artifact storage and is not free-when-idle.
//! - `README.md` — operator-facing apply instructions.
//!
//! Pure function — no I/O. The writer (`crate::credentials::write_rules_pack`)
//! lands these on disk inside the bootstrap flock. The project id is a
//! placeholder the admin substitutes at apply time: `bootstrap` has no reader
//! for the binding's wizard answers (the C6 ↔ Phase D scope split), so it
//! cannot know the project id when it renders.

use crate::credentials::{RulesPack, RulesPackEntry};

/// Input for [`render_bootstrap_rules_pack`]. Borrowed; no heap cost.
pub struct GcpBootstrapInput<'a> {
    /// Env this pack is scoped to — used in resource names + labels.
    pub env_id: &'a str,
    /// Operator-supplied admin identity for the README (the principal that will
    /// run `terraform apply`). Free-form; rendered as a comment.
    pub admin_identity_hint: &'a str,
    /// IAM permissions the custom role will grant. Mirrors the validate-time
    /// permission list 1:1.
    pub permissions: &'a [&'static str],
}

/// Render the rules pack. Pure function — no I/O.
pub fn render_bootstrap_rules_pack(input: &GcpBootstrapInput<'_>) -> RulesPack {
    RulesPack {
        entries: vec![
            RulesPackEntry {
                filename: "gcp-cloudrun-bootstrap.tf".into(),
                content: render_terraform(input),
                description: Some(format!(
                    "Minimum-privilege Cloud Run deployer service account + custom IAM role \
                     for Greentic env `{}`.",
                    input.env_id
                )),
            },
            RulesPackEntry {
                filename: "README.md".into(),
                content: render_readme(input),
                description: Some(
                    "Apply instructions for the GCP Cloud Run bootstrap rules pack.".into(),
                ),
            },
        ],
    }
}

fn render_terraform(input: &GcpBootstrapInput<'_>) -> String {
    let env_id = input.env_id;
    // Terraform resource names must match [a-zA-Z0-9_]; GCP resource ids
    // (SA account_id, role_id) tolerate dashes. Underscore the TF-local names,
    // keep dashes in the GCP-facing ids for readability.
    let env_id_safe = env_id.replace('-', "_");

    let permission_lines = input
        .permissions
        .iter()
        .map(|p| format!("      \"{p}\","))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"# Greentic env-pack bootstrap — GCP Cloud Run deployer credentials.
#
# Apply this with `tofu apply` (preferred) or `terraform apply` against the GCP
# project that will host the Greentic env `{env_id}`. It creates the service
# account Greentic uses at deploy time and a minimum-privilege custom role bound
# to it — the exact permission set `gtc op credentials requirements {env_id}`
# validates via `projects.testIamPermissions`.
#
# REQUIRED: set your project id. Replace every `<REPLACE_WITH_GCP_PROJECT_ID>`
# below (or pass `-var project_id=...`).
#
# Generated by greentic-deployer; safe to commit to source control.

variable "project_id" {{
  type        = string
  description = "GCP project id that will host Greentic env {env_id}."
  default     = "<REPLACE_WITH_GCP_PROJECT_ID>"
}}

# ── Enable the APIs the deployer drives ──────────────────────────────────────
resource "google_project_service" "run_{env_id_safe}" {{
  project            = var.project_id
  service            = "run.googleapis.com"
  disable_on_destroy = false
}}

resource "google_project_service" "secretmanager_{env_id_safe}" {{
  project            = var.project_id
  service            = "secretmanager.googleapis.com"
  disable_on_destroy = false
}}

# ── Deployer + runtime service accounts ──────────────────────────────────────
resource "google_service_account" "greentic_{env_id_safe}_deployer" {{
  project      = var.project_id
  account_id   = "gtc-{env_id}-deployer"
  display_name = "Greentic deployer for env {env_id}"
}}

# Identity the Cloud Run revisions run as (least privilege; the deployer passes
# it via iam.serviceAccounts.actAs).
resource "google_service_account" "greentic_{env_id_safe}_runtime" {{
  project      = var.project_id
  account_id   = "gtc-{env_id}-runtime"
  display_name = "Greentic Cloud Run runtime for env {env_id}"
}}

# ── Minimum-privilege custom role bound to the deployer SA ────────────────────
resource "google_project_iam_custom_role" "greentic_{env_id_safe}_deployer" {{
  project     = var.project_id
  role_id     = "greentic_{env_id_safe}_deployer"
  title       = "Greentic Cloud Run deployer ({env_id})"
  description = "Minimum permissions the Greentic Cloud Run deployer exercises."
  permissions = [
{permission_lines}
  ]
}}

resource "google_project_iam_member" "greentic_{env_id_safe}_deployer_binding" {{
  project = var.project_id
  role    = google_project_iam_custom_role.greentic_{env_id_safe}_deployer.id
  member  = "serviceAccount:${{google_service_account.greentic_{env_id_safe}_deployer.email}}"
}}

# ── OPTIONAL (opt-in): Artifact Registry remote repo proxying ghcr.io ─────────
# Off by default: a remote repository bills for cached-artifact storage, so it
# is NOT free-when-idle. Uncomment for the higher-availability case Google
# recommends (or for later private images), then set `ar_repo` in the wizard
# answers to this repository id.
#
# resource "google_project_service" "artifactregistry_{env_id_safe}" {{
#   project            = var.project_id
#   service            = "artifactregistry.googleapis.com"
#   disable_on_destroy = false
# }}
#
# resource "google_artifact_registry_repository" "greentic_{env_id_safe}_ghcr" {{
#   project       = var.project_id
#   location      = "<REPLACE_WITH_REGION>"
#   repository_id = "gtc-ghcr-mirror"
#   format        = "DOCKER"
#   mode          = "REMOTE_REPOSITORY"
#   remote_repository_config {{
#     description = "Remote repo proxying ghcr.io for Greentic runtime images."
#     docker_repository {{
#       custom_repository {{
#         uri = "https://ghcr.io"
#       }}
#     }}
#   }}
# }}

output "deployer_service_account_email" {{
  description = "Email of the Greentic deployer service account for env {env_id}. Bind this to the env's credentials_ref."
  value       = google_service_account.greentic_{env_id_safe}_deployer.email
}}

output "runtime_service_account_email" {{
  description = "Email of the Cloud Run runtime service account for env {env_id}."
  value       = google_service_account.greentic_{env_id_safe}_runtime.email
}}
"#,
        env_id = env_id,
        env_id_safe = env_id_safe,
        permission_lines = permission_lines,
    )
}

fn render_readme(input: &GcpBootstrapInput<'_>) -> String {
    let permission_bullets = input
        .permissions
        .iter()
        .map(|p| format!("- `{p}`"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"# GCP Cloud Run bootstrap rules pack — env `{env_id}`

Generated by `gtc op credentials bootstrap {env_id}` for the
`greentic.deployer.gcp-cloudrun` env-pack.

## What this is

A minimum-privilege Cloud Run **deployer service account** + custom IAM role
your GCP admin reviews and applies into the project that will host Greentic env
`{env_id}`. The custom role grants only the permissions Greentic's Cloud Run
deploy surface exercises (the same set `gtc op credentials requirements
{env_id}` validates via `projects.testIamPermissions`):

{permission_bullets}

It also creates a least-privilege **runtime service account** the Cloud Run
revisions run as, and enables the Cloud Run + Secret Manager APIs.

Artifact Registry is **not** enabled by default: Cloud Run deploys the public
GHCR image directly, so an idle env costs nothing. A remote-repository mirror
(commented out in the `.tf`) is opt-in for the higher-availability case and
bills for cached-artifact storage.

## How to apply

1. Review `gcp-cloudrun-bootstrap.tf`. Set your project id (replace
   `<REPLACE_WITH_GCP_PROJECT_ID>` or pass `-var project_id=...`). The admin
   applying this is:

   ```
   {admin_hint}
   ```

2. From this directory, authenticated to GCP as a project admin:

   ```sh
   tofu init && tofu apply
   # or: terraform init && terraform apply
   ```

   Use your own remote state backend (GCS, Terraform Cloud, …). Greentic does
   not manage Terraform state for you.

3. Capture the deployer service account email:

   ```sh
   tofu output -raw deployer_service_account_email
   # gtc-{env_id}-deployer@<project>.iam.gserviceaccount.com
   ```

4. Bind it to env `{env_id}`'s credentials backend:

   ```sh
   gtc op credentials rotate {env_id} --provided-credentials-ref \
     "secret://{env_id}/gcp-cloudrun/deployer-sa"
   ```

5. Re-run requirements:

   ```sh
   gtc op credentials requirements {env_id}
   ```

   All capabilities (`{caller_cap}` + the permissions above) must pass before
   `gtc op env up {env_id}` is honored.

## Least-privilege caveat (review before applying)

The custom role above is bound at **project scope**, and project IAM policies
flow down to every resource in the project. In a **shared project** that is
broader than one environment needs: the deployer could `actAs` unrelated service
accounts, read unrelated secrets, and mutate other environments' Cloud Run
Services. Before production use, tighten this to least privilege:

- Grant `iam.serviceAccounts.actAs` (via `roles/iam.serviceAccountUser`) on the
  **runtime service account resource** only — not project-wide.
- Grant the runtime service account `roles/secretmanager.secretAccessor` on
  **this environment's secrets** only (the deploy binds this per-secret when it
  creates them; revisions that mount secrets cannot start without it).
- Add IAM Conditions or resource-scoped bindings for the destructive
  `run.services.*` / `run.revisions.*` verbs so one env cannot mutate another's.

A dedicated project per environment sidesteps all of the above. The per-secret
accessor binding is applied automatically at deploy time; resource-scoped
credential validation is wired in a later step of the Cloud Run deployment train.

## What this does NOT do

This is the credentials bootstrap. The Cloud Run Services, revisions, and Secret
Manager secrets are created by `gtc op env up {env_id}` at deploy time using the
service account this pack provisions.
"#,
        env_id = input.env_id,
        admin_hint = input.admin_identity_hint,
        caller_cap = super::credentials::GCP_CALLER_IDENTITY_CAP,
        permission_bullets = permission_bullets,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn input<'a>(env_id: &'a str, admin_hint: &'a str) -> GcpBootstrapInput<'a> {
        GcpBootstrapInput {
            env_id,
            admin_identity_hint: admin_hint,
            permissions: &["run.services.create", "secretmanager.secrets.create"],
        }
    }

    #[test]
    fn renders_two_entries_tf_and_readme() {
        let pack = render_bootstrap_rules_pack(&input("prod-eu", "admin@example.com"));
        assert_eq!(pack.entries.len(), 2);
        let names: Vec<&str> = pack.entries.iter().map(|e| e.filename.as_str()).collect();
        assert!(names.contains(&"gcp-cloudrun-bootstrap.tf"));
        assert!(names.contains(&"README.md"));
    }

    #[test]
    fn tf_lists_every_permission_and_core_resources() {
        let input = GcpBootstrapInput {
            env_id: "prod-eu",
            admin_identity_hint: "admin@example.com",
            permissions: &[
                "run.services.create",
                "run.services.setIamPolicy",
                "secretmanager.versions.add",
            ],
        };
        let pack = render_bootstrap_rules_pack(&input);
        let tf = &pack
            .entries
            .iter()
            .find(|e| e.filename == "gcp-cloudrun-bootstrap.tf")
            .unwrap()
            .content;
        for perm in input.permissions {
            assert!(
                tf.contains(&format!("\"{perm}\"")),
                "tf must list permission `{perm}`; content:\n{tf}"
            );
        }
        assert!(tf.contains("google_service_account"));
        assert!(tf.contains("google_project_iam_custom_role"));
        assert!(tf.contains("google_project_iam_member"));
        assert!(tf.contains("run.googleapis.com"));
        assert!(tf.contains("secretmanager.googleapis.com"));
        assert!(tf.contains("<REPLACE_WITH_GCP_PROJECT_ID>"));
    }

    #[test]
    fn tf_uses_safe_resource_name_dashes_to_underscores() {
        let pack = render_bootstrap_rules_pack(&input("prod-eu-west1", "admin@example.com"));
        let tf = &pack
            .entries
            .iter()
            .find(|e| e.filename == "gcp-cloudrun-bootstrap.tf")
            .unwrap()
            .content;
        assert!(
            tf.contains("greentic_prod_eu_west1_deployer"),
            "TF-local names underscore dashes; content:\n{tf}"
        );
        // The GCP-facing account_id keeps dashes for readability.
        assert!(tf.contains("gtc-prod-eu-west1-deployer"));
    }

    #[test]
    fn artifact_registry_is_opt_in_and_commented_out() {
        let pack = render_bootstrap_rules_pack(&input("prod-eu", "admin@example.com"));
        let tf = &pack
            .entries
            .iter()
            .find(|e| e.filename == "gcp-cloudrun-bootstrap.tf")
            .unwrap()
            .content;
        // The AR block is present but every one of its resource lines is
        // commented out (off by default per plan D3).
        assert!(tf.contains("google_artifact_registry_repository"));
        for line in tf.lines() {
            if line.contains("google_artifact_registry_repository")
                || line.contains("artifactregistry.googleapis.com")
            {
                assert!(
                    line.trim_start().starts_with('#'),
                    "Artifact Registry lines must be commented out; got: {line}"
                );
            }
        }
    }

    #[test]
    fn readme_lists_permissions_and_apply_and_rotate_commands() {
        let input = GcpBootstrapInput {
            env_id: "prod-eu",
            admin_identity_hint: "admin@example.com",
            permissions: &["run.services.create", "run.services.delete"],
        };
        let pack = render_bootstrap_rules_pack(&input);
        let readme = &pack
            .entries
            .iter()
            .find(|e| e.filename == "README.md")
            .unwrap()
            .content;
        for perm in input.permissions {
            assert!(
                readme.contains(&format!("- `{perm}`")),
                "readme must bullet `{perm}`"
            );
        }
        assert!(readme.contains("tofu apply"));
        assert!(readme.contains("gtc op credentials rotate prod-eu"));
        assert!(readme.contains("env `prod-eu`"));
        // The least-privilege caveat must warn about the project-scope binding.
        assert!(readme.contains("Least-privilege caveat"));
        assert!(readme.contains("shared project"));
    }
}
